import { ChakraProvider } from "@chakra-ui/react";
import "../styles/globals.css";
import '../styles/nprogress.css';
import theme from "../theme/theme";
import Router from "next/router";
import Link from "next/link";
import Head from "next/head";
import NProgress from "nprogress";
import Navbar from "./components/Navbar";

Router.events.on("routeChangeStart", (url) => {
  console.log(`Loading: ${url}`);
  NProgress.start();
});
Router.events.on("routeChangeComplete", () => NProgress.done());
Router.events.on("routeChangeError", () => NProgress.done());

function MyApp({ Component, pageProps }) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Maanav Dalal | PM, Leader, Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png"/>
        <link rel="manifest" href="/icons/site.webmanifest"/>
        <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color="#004255"/>
        <link rel="shortcut icon" href="/icons/favicon.ico"/>
        <meta name="msapplication-TileColor" content="#ffffff"/>
        <meta name="msapplication-config" content="/icons/browserconfig.xml"/>
        <meta name="theme-color" content="#ffffff"/>

        <meta
          name="description"
          content="Software Engineering student at McMaster University focused on growth opportunities and improving my skills in full stack development.  UX / UI Freelancer."
        />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <meta name="theme-color" content="#3182CE" />
        <meta name="theme-color" content="#ffffff" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          property="og:title"
          content="Maanav Dalal | Developer, Leader, Designer"
        />
        <meta
          property="og:description"
          content="Software Engineering student at McMaster University focused on growth opportunities and improving my skills in full stack development. UX / UI Freelancer."
        />
        <meta
          property="og:image"
          content="https://i.ibb.co/hyCwDWf/Web-Splash.png"
        />
        <meta property="og:url" content="https://maanavdalal.com/" />
        <meta property="og:type" content="website" />
      </Head>
      <Navbar></Navbar>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}

export default MyApp;
