name: PyTorch Issues to ONNX Board

# Controls when the workflow will run
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  markdownList:
    name: List open issues labeled "out-of-office"
    runs-on: ubuntu-latest
    steps:
      - name: List onnx issues updated today
        uses: lee-dohm/select-matching-issues@v1
        with:
          format: list
          # query: 'label:"model: onnx" updated:$TODAY'
          query: "updated:$(date +'%Y-%m-%d')"
          token: ${{ secrets.G_TOKEN }}
      - name: Echo issues
        run: echo ${{ steps.bugs.outputs.path }}