name: Sync Issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Testing workflow
    steps:       
    - uses: danhellem/github-actions-issue-to-work-item@master
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: 'maanavorg'
        ado_project: 'testboards' 
        ado_new_state: 'Doing'
        ado_wit: 'New Item' 
        ado_close_state: 'Closed'
        ado_active_state: 'Active'  
        ado_bypassrules: true
        log_level: 100
